name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Signed APK
      uses: victorbnl/build-signed-apk@main
      with:
        keystore_b64: ${{ secrets.keystore_b64 }}
        keystore_password: ${{ secrets.keystore_password }}
        key_alias: ${{ secrets.key_alias }}
        key_password: ${{ secrets.key_password }}
        java_version: 21

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        name: shopping_center_release.apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
          

